# Generated by Django 2.2.24 on 2023-11-03 18:27

from django.db import migrations


def update_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_years__gt=2014).update(new_building=True)
    Flat.objects.filter(construction_years__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(update_new_building),
    ]
