# Generated by Django 2.2.24 on 2023-11-04 14:11

from django.db import migrations
import phonenumbers


def fix_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        phonenumber = flat.owners_phonenumber
        parsed_phonenumber = phonenumbers.parse(phonenumber, 'RU')
        fixed_phonenumber = phonenumbers.format_number(parsed_phonenumber, phonenumbers.PhoneNumberFormat.E164)
        flat.owner_pure_phone = fixed_phonenumber
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20231104_1705'),
    ]

    operations = [
        migrations.RunPython(fix_phonenumbers),
    ]
