# Generated by Django 2.2.24 on 2023-11-04 15:15

from django.db import migrations


def create_owners(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    owners = apps.get_model('property', 'Owner')

    for flat in flats.objects.all().iterator():
        owner, is_created = owners.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )
        owner.flats_in_property.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20231104_1753'),
    ]

    operations = [
        migrations.RunPython(create_owners),
    ]
