# Generated by Django 2.2.24 on 2023-11-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_flat_owners_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phonenumber',
        ),
    ]
