# Generated by Django 2.2.24 on 2023-11-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20231106_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flats_in_property',
            new_name='owned_flats',
        ),
    ]
